#!/usr/bin/env bash
# Generate resume PDFs from HTML and upload to Alibaba Cloud OSS
#
# Chain: HTML (generated by /resume-to-html skill) → PDF (wkhtmltopdf) → OSS (myoss.put.sh)
#
# Usage:
#   ./resume/generate-pdfs.sh              # generate PDFs + upload to OSS
#   ./resume/generate-pdfs.sh --skip-upload # generate PDFs only
#
# Prerequisites:
#   brew install wkhtmltopdf
#   Run /resume-to-html first to generate HTML files from markdown

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OSS_PREFIX="portfolio/resume"
MYOSS="$HOME/Documents/bash/myoss.put.sh"
SKIP_UPLOAD="${1:-}"

RESUMES=("ai-engineer" "fullstack-ai" "senior-swe")

echo "=== Resume PDF Generation ==="

MISSING=()
for name in "${RESUMES[@]}"; do
  md="$SCRIPT_DIR/${name}.md"
  html="$SCRIPT_DIR/${name}.html"
  pdf="$SCRIPT_DIR/${name}.pdf"

  if [ ! -f "$md" ]; then
    continue
  fi

  # Check if HTML exists
  if [ ! -f "$html" ]; then
    MISSING+=("$name")
    continue
  fi

  # Check if HTML is older than markdown (stale)
  if [ "$md" -nt "$html" ]; then
    echo "WARNING: ${name}.html is older than ${name}.md — run /resume-to-html to regenerate"
    MISSING+=("$name")
    continue
  fi

  echo "--- ${name} ---"

  # HTML → PDF with wkhtmltopdf
  wkhtmltopdf \
    --page-size A4 \
    --margin-top 12mm \
    --margin-bottom 8mm \
    --margin-left 14mm \
    --margin-right 14mm \
    --encoding utf-8 \
    --quiet \
    "$html" "$pdf"

  echo "  PDF: ${name}.pdf ($(du -h "$pdf" | cut -f1 | xargs))"
done

# Report missing HTML files
if [ ${#MISSING[@]} -gt 0 ]; then
  echo ""
  echo "WARNING: HTML not found or stale for: ${MISSING[*]}"
  echo "Run /resume-to-html in Claude Code first, then re-run this script."
fi

echo ""

# Upload PDFs to OSS
if [ "$SKIP_UPLOAD" = "--skip-upload" ]; then
  echo "Skipping OSS upload (--skip-upload)"
else
  if [ ! -x "$MYOSS" ]; then
    echo "ERROR: myoss.put.sh not found at $MYOSS"
    echo "Use --skip-upload or fix the path."
    exit 1
  fi

  echo "=== Uploading to OSS ==="
  for name in "${RESUMES[@]}"; do
    pdf="$SCRIPT_DIR/${name}.pdf"
    if [ -f "$pdf" ]; then
      echo "Uploading: ${name}.pdf"
      "$MYOSS" "$pdf" "$OSS_PREFIX"
    fi
  done
fi

echo ""
echo "=== Complete ==="
